config/routes.rb
Rails.application.routes.draw do  
  resources :orders, only: [:index, :new, :create, :show]

  # get 'orders/new'
  # get 'orders/create'
  # get 'orders/show'
  resources :collections do
    post "/finalizar_coleccion" , to: 'collections#finalizar_coleccion'
    get :end_collection , to: 'collections#end_collections'
    get :end_revision , to: 'collections#end_revision'
    get :noviable_collection , to: 'collections#noviable_collection'
    get :redefinir_collection , to: 'collections#redefinir_collection'
    resources :articles
  end 
  get :booking_delayed , to: 'providers#booking_delayed'
  get :booking_canceled , to: 'providers#booking_canceled'
  get :continuar_provedor , to: 'providers#continuar_provedor'
  get :cambiar_provedor , to: 'providers#cambiar_provedor'
  get :finalizar_pedido , to: 'orders#finalizar_pedido'
  get :recepcion_lotes , to: 'orders#recepcion_lotes'
  post :create_bookings_makers, to: 'bookings#create_bookings_makers'
  post :nueva_bookings, to: 'bookings#nueva_bookings'
  resources :makers
  resources :providers
  resources :bookings 
  resources :order_items
  devise_for :users
   root "collections#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  include AASM

  aasm do
    state :started, initial: true
    state :in_review #esperando ser aprobada por el ingeniero que la revisa  
    state :approved  #aprobada por un ingenieros, es decir es viable y no debe redefinirse
    state :waiting_to_materials # esperando respuesta de los proveedores de materiales
    state :waiting_to_makers # esperando respuesta de los lugares de fabricacion
    state :waiting_to_be_completed #esperando ser compleda (que se cumplan todos los vencimientos de las reservas)
    state :redefine #cuando debe redefinirse
    state :finished

    event :in_review do
      transitions from: [:started, :waiting_to_materials, :redefine], to: :in_review
    end

    event :started do
      transitions from: :in_review, to: :started
    end

    event :approved do
      transitions from: :in_review, to: :approved
    end

    event :redefine do
      transitions from: :in_review, to: :redefine
    end

    event :waiting_to_materials do
      transitions from: :approved, to: :waiting_to_materials
    end

    event :waiting_to_makers do
      transitions from: :waiting_to_materials, to: :waiting_to_makers
    end

    event :waiting_to_be_completed do
      transitions from:  :waiting_to_makers, to: :waiting_to_be_completed
    end

    event :finish do
      transitions form: :waiting_to_be_completed, to: :finished
    end
  end

  before_create :set_owner

  belongs_to :owner, foreign_key: :owner, class_name: "User", optional: true
  has_many :articles, dependent: :destroy
  has_many :orders, dependent: :destroy
  scope :by_user, ->(user) { where(owner_id: user.id) }

  def owner
    @owner = User.find(self.owner_id).email
  end

  def enviar_a_revision
    
      in_review! if self.aasm_state == "started" || self.aasm_state == "waiting_to_materials" || self.aasm_state == "redefine"
  end 

  def enviar_a_redefinir    
    redefine! if self.aasm_state == "in_review"
  end 

  def aprobar_coleccion 
    approved! if self.aasm_state == "in_review"
  end 

  def esperar_resultados_materiales
    waiting_to_materials! if self.aasm_state == "approved"
  end 

  def esperar_resultados_lugares
    waiting_to_makers! if self.aasm_state == "waiting_to_materials"
  end 

  def esperar_entregas
    waiting_to_be_completed! if self.aasm_state == "waiting_to_makers"
  end 

  def finalizar_coleccion
    finish! if self.aasm_state == "waiting_to_be_completed"
  end 

  def pending?
    BonitaApi.login
    @pending = BonitaApi.next_task(self.id_i_bonita, 'Analiza si sigue con el provedor')
    return !@pending.nil?
  end

  def canceled?
    BonitaApi.login
    @canceled = BonitaApi.next_task(self.id_i_bonita, 'Analiza respuesta de material')
    return !@canceled.nil?
  end

  def waiting_pedidos?
    BonitaApi.login
    @pedidos = BonitaApi.next_task(self.id_i_bonita, 'Recepción de pedidos')
    return !@pedidos.nil?
  end

  def waiting_recepcion_lotes?
    BonitaApi.login
    @lotes = BonitaApi.next_task(self.id_i_bonita, 'Recepción verificación y asignacion  de lotes')
    return !@lotes.nil?
  end

  def analizar_materiales?
    BonitaApi.login
    @mate = BonitaApi.next_task(self.id_i_bonita, 'Analiza los materiales disponibles')
    return !@mate.nil?
  end

  def analizar_lugares?
    BonitaApi.login
    @lug = BonitaApi.next_task(self.id_i_bonita, 'Analiza los posibles lugares de fabricacion')
    return !@lug.nil?
  end

  def definir_coleccion?
    BonitaApi.login
    @defi = BonitaApi.next_task(self.id_i_bonita, 'Definicion de la coleccion.')
    return !@defi.nil?
  end


  def revision_coleccion?
    BonitaApi.login
    @revi = BonitaApi.next_task(self.id_i_bonita, 'Revision de coleccion')
    return !@revi.nil?
  end

  def esperando_lotes?
    BonitaApi.login
    @lo = BonitaApi.next_task(self.id_i_bonita, 'Recepción verificación y asignacion  de lotes')
    return !@lo.nil?
  end

  private

  def set_owner
    self.owner_id = Current.user.id
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  require 'json'
  
  skip_before_action :authenticate_user!, only: :finalizar_coleccion
  before_action :set_collection, only: %i[ show edit update destroy ]

  # GET /collections or /collections.json
  def index 
    # if Current.user.engineer? || Current.user.designer?
    #   @collections = Collection.all
    # #   @collections = Collection.where(aasm_state: ["in_review", "approved", "waiting_to_materials", "waiting_to_makers", "waiting_to_be_completed"])
    # # elsif Current.user.designer?

    # #   @collections = Collection.where(owner_id: current_user.id, aasm_state: ["started", "redefine"])
    # else
    #   redirect_to orders_path
    # end 
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show
    BonitaApi.login
    #@collections = Collection.where(owner_id: current_user.id)
    @collection = Collection.find(params[:id]) # Busca la colección por su id 
   #@materials = Material.find_by_sql(["SELECT materials.name, SUM(article_materials.quantity) AS total_quantity FROM materials JOIN article_materials ON materials.id = article_materials.material_id JOIN articles ON article_materials.article_id = articles.id JOIN collections ON articles.collection_id = collections.id WHERE collections.id = ? GROUP BY materials.name", @collection.id]) # Ejecuta la consulta y guarda el resultado en @materials 
    @materials = Material.find_by_sql(["SELECT materials.name, SUM(article_materials.quantity) AS total_quantity, MAX(article_materials.presupuesto) AS max_presupuesto FROM materials JOIN article_materials ON materials.id = article_materials.material_id JOIN articles ON article_materials.article_id = articles.id JOIN collections ON articles.collection_id = collections.id WHERE collections.id = ? GROUP BY materials.name", @collection.id])
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    #Se loguea en bonita
    BonitaApi.login
    #pide a bonita el id del proceso que esta corriendo en su servidor llamado 'coleccion'
    #este nombre es el que tiene en el diagrama de procesos
    process_id = BonitaApi.get_process_id('coleccion')    
    #con el id inicia una instancia de proceso o caso
    @process_instance = BonitaApi.start_process(process_id)
    @collection = Collection.new(collection_params)
    #se guarda el id del caso en la coleccion
    @collection.id_i_bonita = @process_instance

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
  
    BonitaApi.login
    BonitaApi.delete_case(@collection.id_i_bonita)
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

 def all_user
      @collection = Collection.find_by(owner_id: Current.user.id)
 end

 def end_collections  
  BonitaApi.login
  @collection = Collection.find( params[:collection_id])
  @collection.enviar_a_revision
  #como sabe que esta pendiente la tarea de definir pide la siguiente task del case
  @current_task = BonitaApi.current_task(@collection.id_i_bonita)
  BonitaApi.assigned_task(@current_task)
  BonitaApi.complete_task(@current_task)
  redirect_to root_path
 end

 def end_revision
  BonitaApi.login
  @collection = Collection.find(params[:collection_id])
  @current_task = BonitaApi.current_task(@collection.id_i_bonita)
  BonitaApi.assigned_task(@current_task)
 # @current_task = BonitaApi.current_task(@collection.id_i_bonita)
  @collection.aprobar_coleccion
  @materials = Material.find_by_sql(["SELECT materials.name, SUM(article_materials.quantity) AS total_quantity, MAX(article_materials.presupuesto) AS max_presupuesto FROM materials JOIN article_materials ON materials.id = article_materials.material_id JOIN articles ON article_materials.article_id = articles.id JOIN collections ON articles.collection_id = collections.id WHERE collections.id = ? GROUP BY materials.name", @collection.id])
  json = {
    "materials": @materials.map do |h|
      {
        "material": h["name"].downcase,
        "stock": h["total_quantity"],
        "price": h["max_presupuesto"].to_f,
        "date": @collection.release_date # es la fecha en la que el ingeniero va a tener el lugar de fabricacion
      }
    end
  }.to_json  
    #seteo variables del proceso
  BonitaApi.set_variable("consultaMateriales", "#{json}", "java.lang.String", @collection.id_i_bonita)
  BonitaApi.set_variable("viable", "true", "java.lang.Boolean", @collection.id_i_bonita)
  BonitaApi.set_variable("redefinir", "false", "java.lang.Boolean", @collection.id_i_bonita)
  #finalizo la tarea 
  BonitaApi.complete_task(@current_task)
  @collection.esperar_resultados_materiales
  redirect_to root_path
 end


 def noviable_collection
  BonitaApi.login
  @collection = Collection.find( params[:collection_id])
  @current_task = BonitaApi.current_task(@collection.id_i_bonita)
  BonitaApi.assigned_task(@current_task)
  #seteo variables del proceso
  BonitaApi.set_variable("viable", "false", "java.lang.Boolean", @collection.id_i_bonita)
  BonitaApi.complete_task(@current_task)   #finalizo la tarea 
  @collection.destroy   #borro la coleccion
  redirect_to root_path
 end

 def redefinir_collection
  BonitaApi.login
  @collection = Collection.find( params[:collection_id])
  @current_task = BonitaApi.current_task(@collection.id_i_bonita)
  BonitaApi.assigned_task(@current_task)
  #seteo variables del proceso
  BonitaApi.set_variable("viable", "true", "java.lang.Boolean", @collection.id_i_bonita)
  BonitaApi.set_variable("redefinir", "true", "java.lang.Boolean", @collection.id_i_bonita)
  BonitaApi.complete_task(@current_task)   #finalizo la tarea 
  @collection.enviar_a_redefinir
  redirect_to root_path
 end

 def finalizar_coleccion 
  @collection = Collection.find_by(id_i_bonita: params[:collection_id])
  @collection.finalizar_coleccion
  #render json: "Se finalizo la coleccion", status: :ok
  respond_to do |format|
    format.html { redirect_to root_path, notice: "ok" }
    #format.json { head :no_content }
    format.json { render :index, status: :ok, location: @collection }
  end
 end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end
   # ...

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:release_date, :name, :owner_id, :manufacturing_lead_time, :estimated_release_date, :budget, articles_attributes: [:id, :model, :category_id, :description]) # permite los atributos de los artículos anidados
    end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @collection.name %></h5>
    <div class=" justify-content-md-start">
    <p class="card-text">
      <strong><%= t('.owner') %></strong>
      <%= @collection.owner %>
    </p>
    <p class="card-text">
      <strong><%= t('.manufacturing_lead_time') %></strong>
      <%= @collection.manufacturing_lead_time %>
    </p>
    <p class="card-text">
      <strong><%= t('.estimated_release_date') %></strong>
      <%= @collection.estimated_release_date %>
    </p>
    <% if !@collection.revision_coleccion? %>
      <strong><%= "Presupuesto de fabricacion:" %></strong>
      <%= @collection.budget %>
    <% end %>
    <% if current_user.engineer? && @collection.revision_coleccion? %>
      <%= form_with(model: @collection, local: true) do |f| %>
        <div class="field">
          <strong><%= f.label "Presupuesto de fabricacion:" %></strong>
          <%= f.number_field :budget %>
        </div>
        <div class="field">
          <strong><%= f.label "Fecha de inicio:" %></strong>
          <%= f.date_field :release_date %>
        </div>
        <div class="actions">
          <%= f.submit "Guardar" %>
        </div>
      <% end %>
    <% end %>

    </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <% if Current.user.designer? && @collection.definir_coleccion? %>
        <%= link_to t('.edit'), edit_collection_path(@collection), class: "btn btn-warning me-md-2" %> 
        <%= button_to t('.delete'), @collection, method: :delete, class: "btn btn-danger me-md-2" %>
        <%= link_to  t('.add'), new_collection_article_path(@collection), method: :post, class: "btn btn-success me-md-2" %>
        <%= button_to 'Enviar a revision', collection_end_collection_path(@collection), method: :get %>
      <% elsif current_user.engineer? && @collection.revision_coleccion? %>
     
        <%= link_to  'No viable', collection_noviable_collection_path(@collection), method: :get, class: "btn btn-danger me-md-2" %> 
        <%= link_to  'Redefinir', collection_redefinir_collection_path(@collection), method: :get, class: "btn btn-warning me-md-2" %> 
        <%= link_to  'Aceptar y completar', collection_end_revision_path(@collection), method: :get, class: "btn btn-success me-md-2" %> 
      <% end %>

    </div>
      <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%= t('.articles') %></th>
        <th><%= t('.actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.articles.each do |article| %>
        <tr>
          <td><%= article.model %></td>
          <td>
           <li class="list-group-item"> <%= link_to t('.view') , collection_article_path(@collection, article), class: "btn btn-primary" %></li>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if current_user.engineer? %>
  <%= content_tag :table, class: "table table-striped table-hover" do %> 
    <%= content_tag :thead do %> 
      <%= content_tag :tr do %> 
        <%= content_tag :th, "Nombre del material" %> 
        <%= content_tag :th, "Cantidad de unidades" %> 
        <%= content_tag :th, "Maximo presupuesto por unidad" %> 
      <% end %> 
    <% end %> 
    <%= content_tag :tbody do %> 
      <% @materials.each do |material| %> 
        <%= content_tag :tr do %> 
          <%= content_tag :td, material.name %> 
          <%= content_tag :td, material.total_quantity %> 
          <%= content_tag :td, material.max_presupuesto %>
        <% end %> 
      <% end %> 
    <% end %> 
  <% end %>
  <% end %>
  </div>
</div>

app/views/collections/_form.html.erb
<div id="collections" class="container mt-4">
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label t('.name') , class: "form-label" %>
    <%= form.text_field :name, class: "form-control form-control-blue-100" %>
  </div>

  <div class="mb-3">
    <%= form.label  t('.manufacturing_lead_time'), class: "form-label" %>
    <%= form.number_field :manufacturing_lead_time, class: "form-control form-control-pink-100" %>
  </div>

  <div class="mb-3">
    <%= form.label t('.estimated_release_date'), class: "form-label" %>
    <%= form.date_field :estimated_release_date, class: "form-control form-control-green-100" %>
  </div>
  </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= form.submit "Guardar cambios", class: "btn btn-primary", id: "submit-button" %>
  </div>
  
<% end %>
</div>

app/views/collections/edit.html.erb
<h1><%= t('.edit') %></h1>

<%= render "form", collection: @collection %>

<br>

app/views/collections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="display-4 text-center text-gray-800"> <%= t('.collection') %></h1>

<div id="collections" class="container mt-4">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%= t('.name') %></th>
        <th><%= t('.actions') %></th>
        <th><%= t('Estado') %></th>
      </tr>
    </thead>
    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td><%= collection.name %></td>
          <td>
          <% if Current.user.designer? %>
            <% if collection.definir_coleccion? %>
            <%= link_to t('.view'), collection, class: "btn btn-primary" %>
              <%= link_to t('.delete'), collection, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-danger" %>
              <%= link_to t('.editar'), edit_collection_path(collection), class: "btn btn-secondary" %>  
            <% else %>
              <%= link_to t('.view'), collection, class: "btn btn-primary" %>  
            <% end %>    
          <% end %>
          <% if current_user.engineer? %>
            <% if collection.analizar_materiales? %>
              <%= link_to 'Ver proveedores', providers_path(collection_id: collection) , class: "btn btn-success" %>
            <% elsif collection.analizar_lugares?  %>
              <%= link_to 'Ver lugares', makers_path(collection_id: collection), class: "btn btn-success" %>      
            <% elsif collection.waiting_pedidos? && !collection.pending? && !collection.canceled?%>
              <%= link_to t('.view'), collection, class: "btn btn-primary" %>  
            <% elsif collection.revision_coleccion? %>
              <%= link_to t('.view'), collection, class: "btn btn-primary" %> 
            <% elsif collection.pending? %>
              <%= link_to t('.view'), collection, class: "btn btn-primary" %>  
              <%= link_to "Ver Entrega atrasada", booking_delayed_path(collection_id: collection), class: "btn btn-primary" %>  
            <% elsif collection.canceled? %>
              <%= link_to t('.view'), collection, class: "btn btn-primary" %>  
              <%= link_to "Ver posibles proveedores", booking_canceled_path(collection_id: collection), class: "btn btn-primary" %> 
            <% end %>
          <% end %>
          <% if current_user.marketing? %>
            <% if collection.waiting_pedidos? %>
              <%= link_to 'Agregar pedido', new_order_path(collection_id: collection) , class: "btn btn-success" %>
              <%= link_to 'Ver Pedidos', orders_path(collection_id: collection) , class: "btn btn-success" %>
              <% end %>
          <% end %>
          <% if current_user.logistica? %>
            <% if collection.esperando_lotes? %>
              <%= link_to 'Recepcion de lotes', recepcion_lotes_path(collection_id: collection) , class: "btn btn-success" %>
            <% end %>
          <% end %>
          </td>
          <td><%= collection.aasm_state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if Current.user.designer? %>
    <%= link_to t('.new'), new_collection_path, class: "btn btn-success" %>
  <% end %>
</div>

app/views/collections/new.html.erb
<h1>Nueva colección</h1>

<%= render "form", collection: @collection %>

<br>

app/views/collections/show.html.erb
<div id="collections" class="container mt-4">
    <%= render "collection", collection: @collection %>
</div>