config/routes.rb
Rails.application.routes.draw do  
  resources :orders, only: [:index, :new, :create, :show]

  # get 'orders/new'
  # get 'orders/create'
  # get 'orders/show'
  resources :collections do
    post "/finalizar_coleccion" , to: 'collections#finalizar_coleccion'
    get :end_collection , to: 'collections#end_collections'
    get :end_revision , to: 'collections#end_revision'
    get :noviable_collection , to: 'collections#noviable_collection'
    get :redefinir_collection , to: 'collections#redefinir_collection'
    resources :articles
  end 
  get :booking_delayed , to: 'providers#booking_delayed'
  get :booking_canceled , to: 'providers#booking_canceled'
  get :continuar_provedor , to: 'providers#continuar_provedor'
  get :cambiar_provedor , to: 'providers#cambiar_provedor'
  get :finalizar_pedido , to: 'orders#finalizar_pedido'
  get :recepcion_lotes , to: 'orders#recepcion_lotes'
  post :create_bookings_makers, to: 'bookings#create_bookings_makers'
  post :nueva_bookings, to: 'bookings#nueva_bookings'
  resources :makers
  resources :providers
  resources :bookings 
  resources :order_items
  devise_for :users
   root "collections#index"
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
    require 'json'
    before_action :authenticate_user!

    def index
        BonitaApi.login
        @collection = Collection.find(params[:collection_id])
        @materiales = BonitaApi.get_variable('respuestaMateriales', @collection.id_i_bonita)

        if @materiales["value"] == "null"
            @providers = nil
        else
 
            @hash_result = JSON.parse(@materiales["value"])
            @providers = @hash_result["data"]["provedores"]
            respond_to do |format|
                format.html # busca la plantilla index.html.erb
                format.json { render json: @providers } # busca la plantilla index.json.erb
            end
            render locals: { collection: @collection }
        end        
      end

    def booking_canceled
        BonitaApi.login
        @collection = Collection.find(params[:collection_id])
        @materiales = BonitaApi.get_variable('nuevaRespuestaMateriales', @collection.id_i_bonita)
        @provider_id_canceleded = BonitaApi.get_variable('providerId', @collection.id_i_bonita)
        @hash_result = JSON.parse(@materiales["value"])
        @filtered_hash = @hash_result["data"]["provedores"].reject { |provedor| provedor["id"] == @provider_id_canceleded["value"].to_i }
        render :template => "providers/indexDos", :format => :html, :locals => {:providers =>  @filtered_hash, :collection => @collection}
    end

    def booking_delayed
        BonitaApi.login
        @collection = Collection.find(params[:collection_id])
        @nuevaReserva = BonitaApi.get_variable('estaApi', @collection.id_i_bonita)
        @booking = JSON.parse(@nuevaReserva["value"])
        render :template => "providers/reservaDelay", :format => :html, :locals => {:booking =>  @booking, :collection => @collection}
    end

    def continuar_provedor
        @collection = Collection.find(params[:collection_id])
        #DateTime.now.advance(days: 5).to_s
        body = {
            "new_date": DateTime.now.advance(minutes: 2).to_s
        }.to_json 
        #seteo la variable con la nueva fecha de entrega
        BonitaApi.login

        BonitaApi.set_variable("fechaActualizada", "#{body}", "java.lang.String", @collection.id_i_bonita) 
        BonitaApi.set_variable("sigue", "true", "java.lang.Boolean", @collection.id_i_bonita)
        @search_task = BonitaApi.search_task(@collection.id_i_bonita, 'Analiza si sigue con el provedor')
        BonitaApi.assigned_task(@search_task)
        BonitaApi.complete_task(@search_task)
        redirect_to root_path , notice: "Se envio la nueva fecha de entrega"  
    end 

    def cambiar_provedor
        @collection = Collection.find(params[:collection_id])
        BonitaApi.login
        BonitaApi.set_variable("sigue", "false", "java.lang.Boolean", @collection.id_i_bonita)
        @search_task = BonitaApi.search_task(@collection.id_i_bonita, 'Analiza si sigue con el provedor')
        BonitaApi.assigned_task(@search_task)
        BonitaApi.complete_task(@search_task)
        redirect_to root_path , notice: "Se vuelve a consultar materiales a la API" 
    end 

end
  

app/views/providers/index.html.erb
<h1>Proveedores</h1>
<% if @providers.nil? %>
  <p>Hasta el momento no se recibió respuesta de los proveedores por su petición, vuelva a consultar mas tarde. </p>
<% elsif @providers.empty? %>
  <p>No hay proveedores disponibles.</p>
  <p>Vuelva a hacer la consulta de materiales.</p>
<% else %>
  <%= form_with model: @booking, url: bookings_path, method: :post do |form| %>
    <%= hidden_field_tag :collection_id, @collection.id%>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>País</th>
        <th>Dirección</th>
        <th>Ciudad</th>
        <th>Materiales</th>
        <th>Precio</th>
        <th>Stock</th>
        <th>Demora en entrega</th>
      </tr>
    </thead>
    <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider["name"] %></td>
        <td><%= provider["country"] %></td>
        <td><%= provider["address"] %></td>
        <td><%= provider["city"] %></td>
        <td><%= provider["provisions"][0]["material"]["name"] %></td>
        <td><%= provider["provisions"][0]["price"] %></td>
        <td><%= provider["provisions"][0]["stock"] %></td>
        <td><%= provider["provisions"][0]["delivery_time"] %> días</td>
        <td><%= check_box_tag "selected_provisions[]", provider["provisions"][0].to_json%></td> 
      </tr>
  <% end %>
    </tbody>
  </table>
  <%= form.submit "Reservar" %> 
<% end %>
<% end %>

app/views/providers/indexDos.html.erb
<h1>Proveedores</h1>
  <%= form_with model: @booking, url: nueva_bookings_path, method: :post do |form| %>
    <%= hidden_field_tag :collection_id, collection.id%>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>País</th>
        <th>Dirección</th>
        <th>Ciudad</th>
        <th>Materiales</th>
        <th>Precio</th>
        <th>Stock</th>
        <th>Demora en entrega</th>
      </tr>
    </thead>
    <tbody>
    <% providers.each do |provider| %>
      <tr>
        <td><%= provider["name"] %></td>
        <td><%= provider["country"] %></td>
        <td><%= provider["address"] %></td>
        <td><%= provider["city"] %></td>
        <td><%= provider["provisions"][0]["material"]["name"] %></td>
        <td><%= provider["provisions"][0]["price"] %></td>
        <td><%= provider["provisions"][0]["stock"] %></td>
        <td><%= provider["provisions"][0]["delivery_time"] %> días</td>
        <td><%= check_box_tag "selected_provisions[]", provider["provisions"][0].to_json%></td> 
      </tr>
  <% end %>
    </tbody>
  </table>
  <%= form.submit "Reservar" %> 
 
<% end %>
<br>
<br>
<%= button_to "cancelar coleccion", @collection, method: :delete, class: "btn btn-danger me-md-2" %>

app/views/providers/reservaDelay.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= "Reserva atrasada" %></h5>
    <div class=" justify-content-md-start">
    <p class="card-text">
      <strong><%= "Material: " %></strong>
      <%= booking["material_name"]%>
    </p>
    <p class="card-text">
      <strong><%= "Provedor: " %></strong>
      <%= booking["provider_id"]%>
    </p>
    <p class="card-text">
      <strong><%= "Precio: " %></strong>
      <%= booking["price"] %>
    </p>
    <p class="card-text">
      <strong><%= "Se demora : " %></strong>
      <%= " 5 días" %>
    </p>
    
    </div>
    <%= link_to "Continuar con el proveedor", continuar_provedor_path(collection_id: collection), class: "btn btn-primary" %> 
    <br>
    <%= link_to "Cambiar el proveedor", cambiar_provedor_path(collection_id: collection), class: "btn btn-primary" %>   
    
     
  
  </div>
</div>