config/routes.rb
Rails.application.routes.draw do  
  resources :orders, only: [:index, :new, :create, :show]

  # get 'orders/new'
  # get 'orders/create'
  # get 'orders/show'
  resources :collections do
    post "/finalizar_coleccion" , to: 'collections#finalizar_coleccion'
    get :end_collection , to: 'collections#end_collections'
    get :end_revision , to: 'collections#end_revision'
    get :noviable_collection , to: 'collections#noviable_collection'
    get :redefinir_collection , to: 'collections#redefinir_collection'
    resources :articles
  end 
  get :booking_delayed , to: 'providers#booking_delayed'
  get :booking_canceled , to: 'providers#booking_canceled'
  get :continuar_provedor , to: 'providers#continuar_provedor'
  get :cambiar_provedor , to: 'providers#cambiar_provedor'
  get :finalizar_pedido , to: 'orders#finalizar_pedido'
  get :recepcion_lotes , to: 'orders#recepcion_lotes'
  post :create_bookings_makers, to: 'bookings#create_bookings_makers'
  post :nueva_bookings, to: 'bookings#nueva_bookings'
  resources :makers
  resources :providers
  resources :bookings 
  resources :order_items
  devise_for :users
   root "collections#index"
end

app/models/article.rb
class Article < ApplicationRecord

  has_many_attached :photos

  belongs_to :category, optional: true
  belongs_to :collection, optional: true

  has_many :article_materials
  has_many :materials, through: :article_materials, dependent: :destroy
  has_many :order_items , dependent: :destroy

  accepts_nested_attributes_for :materials 
  accepts_nested_attributes_for :article_materials



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @collection = Collection.find(params[:collection_id])
  end

  # GET /articles/new
  def new
    @collection = Collection.find(params[:collection_id])
    @article = Article.new 
  end

  # GET /articles/1/edit
  def edit
    @collection = Collection.find(params[:collection_id])
    @article = @collection.articles.find(params[:id])
  end

  # POST /articles or /articles.json
  def create
    @collection = Collection.find(params[:collection_id])
    @article = @collection.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to collection_url(@collection), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  
  def update
    @collection = Collection.find(params[:collection_id])    
    respond_to do |format|
      if @article.update(article_params)
        #@article.photos.append(article_params[:photos])
        format.html { redirect_to collection_article_path(@collection, @article), notice: "Se modifico exitosamente." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    @collection = Collection.find(params[:collection_id])
    respond_to do |format|
      format.html { redirect_to collection_url(@collection), notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

  def article_params
    params.require(:article).permit(:model, :description, :category_id, :collection_id, material_ids: [], photos: [], article_materials_attributes: [:id, :quantity, :presupuesto ])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= "Artículo" %></h5>
    <div class=" justify-content-md-start">

      <p class="card-text">
        <strong><%= t('.collection') %></strong>
        <%= article.collection.try(:name) %>
      </p>

      <p class="card-text">
        <strong><%= t('.model') %></strong>
        <%= article.model %>
      </p>

      <p class="card-text">
        <strong><%= t('.category') %></strong>
        <%= article.category.try(:name) %>
      </p>

      <p class="card-text">
        <strong><%= t('.description') %></strong>
        <%= article.description %>
      </p>
      <% article.photos.each do |photo| %> <img src="<%= url_for(photo) %>"> 
      <% end %>

      <p class="card-text">
        <strong><%= t('.materials') %></strong>
      </p>
    </div>
    <% if Current.user.designer? %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th><%=  %></th>
          </tr>
        </thead>
      <tbody>
        <% article.materials.each do |material| %>
          <tr>
            <td><%= material.name %></td>          
          </tr>
        <% end %>
      </tbody>
      </table>
    <% elsif current_user.engineer? %>
      <%= render partial: "form_materials", locals: {article: @article} %>
    <% end %>     
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, url: collection_articles_path(@collection)) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :category_id, "Categoria", style: "display: block" %>
    <%= form.select :category_id, Category.all.pluck(:name, :id), {} %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :material_ids, "Materiales", style: "display: block" %>
    <%= form.select :material_ids, Material.all.pluck(:name, :id), {}, {multiple: true, size: 5} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_form_edit.html.erb
<%= form_with(model: [@collection, @article]) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
<div class="container mt-4">
  <div class="mb-3">
    <%= form.label 'Modelo', class: "form-label" %>
    <%= form.text_field :model, class: "form-control form-control-blue-100"  %>
  </div>
  <div class="mb-3">
    <%= form.label 'Categoría', class: "form-label", style: "display: block" %>
    <%= form.select :category_id, Category.all.pluck(:name, :id), {}, class: "form-control form-control-blue-100" %>
  </div>

  <div class="mb-3">
    <%= form.label 'Descripción', class: "form-label" %>
    <%= form.text_area :description, class: "form-control form-control-blue-100"%>
  </div>

  <div class="mb-3">
    <%= form.label t('.material_ids'), "Materiales", class: "form-label", style: "display: block"   %>
    <%= form.select :material_ids, Material.all.pluck(:name, :id), {}, {multiple: true, size: 5, class: "form-control form-control-blue-100"}%>
  </div>

  <div class="mb-3">
    <%= form.label "Fotos", class: "form-label", style: "display: block"   %>
    <%= form.file_field :photos, multiple: true %>
  </div>

 <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= form.submit "Guardar cambios", class: "btn btn-primary" %>
 </div>
</div>
<% end %>

app/views/articles/_form_materials.html.erb
<%= label_tag do %> 
    <%= form_with(model:[@collection, @article]) do |f| %>
        <table class=“table table-striped table-hover”> 
        <thead> 
          <tr> 
            <th>Nombre del material</th> 
            <th>Cantidad</th> 
            <th>Presupuesto</th> 
          </tr> 
        </thead> 
      <tbody> 
      <%= f.fields_for :article_materials do |am| %> 
        <tr> 
            <td><%= am.object.material.name %></td> 
            <% if @collection.in_review?  %>
              <td><%= am.number_field :quantity %></td> 
              <td><%= am.number_field :presupuesto %></td> 
            <% else %>
            <td><%= am.number_field :quantity, disabled:true %></td> 
            <td><%= am.number_field :presupuesto , disabled:true %></td> 
            <% end %>
            
        </tr> 
      <% end %>
      </tbody> 
      </table> 
      <% if @collection.in_review? %>
        <%= f.submit "Guardar" %> 
      <% end %> 
    <% end %> 
<% end %>

app/views/articles/edit.html.erb
<div>
    <h1><%= t('.edit') %></h1>
    <%= link_to t('.goback'),  collections_path, class: "btn btn-success" %>
</div>
<%= render "form_edit", article: @article %>
<br>

app/views/articles/new.html.erb
<div>
    <h1><%= t('.new') %></h1>
    <%= link_to t('.goback'), @collection, class: "btn btn-success" %>
</div>
<%= render "form", article: @article %>

<br>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>
<br>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <div id="collections" class="container mt-4">
        <% if Current.user.designer? %>
            <%= link_to t('.edit'), edit_collection_article_path(@article.collection, @article), method: :get, class: "btn btn-warning me-md-2"%>
            <%= button_to t('.delete'), collection_article_path(@article.collection, @article), method: :delete, class: "btn btn-danger me-md-2" %>
        <% end %>
        <%= link_to "volver a coleccion", @collection, class: "btn btn-primary" %>    
    </div>
</div>