config/routes.rb
Rails.application.routes.draw do  
  resources :orders, only: [:index, :new, :create, :show]

  # get 'orders/new'
  # get 'orders/create'
  # get 'orders/show'
  resources :collections do
    post "/finalizar_coleccion" , to: 'collections#finalizar_coleccion'
    get :end_collection , to: 'collections#end_collections'
    get :end_revision , to: 'collections#end_revision'
    get :noviable_collection , to: 'collections#noviable_collection'
    get :redefinir_collection , to: 'collections#redefinir_collection'
    resources :articles
  end 
  get :booking_delayed , to: 'providers#booking_delayed'
  get :booking_canceled , to: 'providers#booking_canceled'
  get :continuar_provedor , to: 'providers#continuar_provedor'
  get :cambiar_provedor , to: 'providers#cambiar_provedor'
  get :finalizar_pedido , to: 'orders#finalizar_pedido'
  get :recepcion_lotes , to: 'orders#recepcion_lotes'
  post :create_bookings_makers, to: 'bookings#create_bookings_makers'
  post :nueva_bookings, to: 'bookings#nueva_bookings'
  resources :makers
  resources :providers
  resources :bookings 
  resources :order_items
  devise_for :users
   root "collections#index"
end

app/models/order.rb
class Order < ApplicationRecord
  # Una orden pertenece a una colección
  belongs_to :collection
  # Una orden tiene muchos items
  has_many :order_items , dependent: :destroy
  # Una orden tiene muchos artículos a través de los items
  has_many :articles, through: :order_items 

  accepts_nested_attributes_for :order_items
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index 
    @orders = Order.where(collection_id: params[:collection_id])
  end 
  def new
    @collection_id = params[:collection_id]
  end

  def create
    # Crear un nuevo pedido con los parámetros permitidos
    @order = Order.new(order_params)
    # Guardar el pedido en la base de datos
    if @order.save
      # Redirigir a la vista del pedido
      redirect_to @order 
    else
      # Mostrar un mensaje de error
      flash[:alert] = "No se pudo crear el pedido"
      # Renderizar la vista new
      render :new
    end
  end

  def show
    # Obtener el pedido por su id
    @order = Order.find(params[:id])
    # Obtener los ítems del pedido
    @order_items = @order.order_items
  end

  def finalizar_pedido
    @order = Order.find(params[:order_id])
    @order.state = "finalizado"
    @order.save
    BonitaApi.login
    @collection = Collection.find( @order.collection_id)
    @search_task = BonitaApi.search_task(@collection.id_i_bonita, 'Recepción de pedidos')
    BonitaApi.assigned_task(@search_task)
    BonitaApi.complete_task(@search_task)
    redirect_to root_path
  end 

  def recepcion_lotes
    @collection = Collection.find( params[:collection_id])
    @collection.finalizar_coleccion
    @search_task = BonitaApi.search_task(@collection.id_i_bonita, 'Recepción verificación y asignacion  de lotes')

    BonitaApi.assigned_task(@search_task)
    BonitaApi.complete_task(@search_task)
    redirect_to root_path

  end

  private

  # Definir los parámetros permitidos para el pedido
 def order_params    
   params.permit(:date_delivery, :collection_id, :customer)
 end

  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="display-4 text-center text-gray-800"> <%= "Pedidos" %></h1>

<div id="orders" class="container mt-4">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%= "Cliente" %></th>
        <th><%= "Collección" %></th>
        <th><%= "Fecha de entrega" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @orders .each do |order| %>
        <tr>
          <td><%= order.customer %></td>
          <td><%= order.collection_id %> </td>
          <td><%= order.date_delivery %></td>
          <td><%= link_to "Ver pedido", order, class: "btn btn-primary" %>  </td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>

app/views/orders/new.html.erb
<!-- app/views/orders/new.html.erb -->
<h1>Nuevo pedido</h1>
<%= form_with model: @order, url: orders_path, method: :post   do |f| %>
  <p>
    <%= f.label :date_delivery, "Fecha de entrega" %>
    <%= f.date_field :date_delivery %>
  </p>

  <%= f.hidden_field :collection_id, value: @collection_id %> 
  <p>
    <%= f.label :customer, "Cliente" %>
    <%= f.text_field :customer %>
  </p>
  
  <p>
    <%= f.submit "Crear pedido" %>
  </p>
<% end %>

app/views/orders/show.html.erb
<!-- app/views/orders/show.html.erb -->
<h1>Pedido</h1>
<p>
  <strong>Fecha de entrega:</strong>
  <%= @order.date_delivery %>
</p>
<p>
  <strong>Colección:</strong>
  <%= @order.collection.name %>
</p>
<p>
  <strong>Cliente:</strong>
  <%= @order.customer %>
</p>

<h2>Artículos</h2>
<table>
  <thead>
    <tr>
      <th>Artículo</th>
      <th>Cantidad</th>
    </tr>
  </thead>
  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.article.model %></td>
        <td><%= order_item.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @order.state != "finalizado" %>
  <%= link_to  "Agregar articulo", new_order_item_path(order_id: @order.id), method: :post, class: "btn btn-success me-md-2" %>
  <%= link_to 'Finalizar Pedido', finalizar_pedido_path(order_id: @order.id), method: :get, class: "btn btn-warning me-md-2" %>
<% end %>